version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: always
    ports:
      - 33306:3306
