version: '3'
networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: always
    ports:
      - 33306:3306
    networks:
      - backend

  python:
    build: ./dock/python
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8888:8000
    depends_on:
      - db
    networks:
      - backend

  node:
    build: ./dock/node
    tty: true
    volumes:
      - ./app/node:/usr/src/app
    ports:
      - 3030:3000
    networks:
      - backend
