version: '3'
networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./.data/conf.d:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: always
    ports:
      - 33306:3306
    networks:
      - backend

  app:
    build: .
    tty: true
    ports:
      - "8888:8000"
    depends_on:
      - db
    networks:
      - backend
