version: '3'
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    restart: always
    ports:
      - 33306:3306
    networks:
      - backend

  web:
    build: ./dock/web
    tty: true
    volumes:
      - ./dock/web/conf/nginx:/etc/nginx/conf.d
    ports:
      - 8000:8000
    depends_on:
      - python
    networks:
      - frontend

  python:
    build: ./dock/python
    command: uwsgi --socket :8080 --module mysite.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    tty: true
    volumes:
      - ./app:/usr/src/app
#    ports:
#      - 8888:8000
    expose:
      - 8080
    depends_on:
      - db
    networks:
      - frontend
      - backend

  node:
    build: ./dock/node
    tty: true
    volumes:
      - ./app/node:/usr/src/app
    ports:
      - 3030:3000
    networks:
      - backend
